# Site settings
title: Denis's Project Blog

author:
  name: Denis J
  email: DenisJ@gmail.ie
description: "Denis's Project./n goat
nig"
description: "Github."

# Build settings
remote_theme: jekyll/minima

plugins:
- jekyll-remote-theme
